// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxzqjyppmpocimplgcbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4enFqeXBwbXBvY2ltcGxnY2JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MDQ3NTAsImV4cCI6MjA3MDA4MDc1MH0.M-9NZmnkL0Iiu-ZwZZlMuY0GaE979N6m5ZC0EHDbPAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});